name: core_common
description: "Common module"

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.0.2+1
  enum_to_string: ^2.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_gen_runner: ^5.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  module:
    androidX: true
    androidPackage: com.flutterexample.modular.common
    iosBundleIdentifier: com.flutterexample.modular.common
