name: feature_detail
description: "Feature detail"

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  core_model:
    path: ../../core/model
  core_common:
    path: ../../core/common
  core_ui:
    path: ../../core/ui
  core_data:
    path: ../../core/data
  core_designsystem:
    path: ../../core/designsystem
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_gen_runner: ^5.4.0
  equatable: ^2.0.5
  hooks_riverpod: ^2.1.3
#  flutter_hooks: ^0.20.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.3
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/gen/
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.detail
    iosBundleIdentifier: com.example.detail
