name: database
description: "Database module"
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  module:
    androidX: true
    androidPackage: com.flutterexample.core.database
    iosBundleIdentifier: com.flutterexample.core.database
