name: core_ui
description: "Ui core module"

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_gen_runner: ^5.4.0
  hooks_riverpod: ^2.1.3
  core_common:
    path: ../common
  fluttertoast: ^8.2.4
  easy_localization: ^3.0.3
  freezed_annotation: ^2.4.1
  core_model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6

# Config generate when build
flutter_gen:
  output: lib/gen/
  line_length: 160
  null_safety: true
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
  fonts:
    enabled: true

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.flutterexample.modular.ui
    iosBundleIdentifier: com.flutterexample.modular.ui
